#import <Foundation/Foundation.h>
#import "../Sources/SSGit.h"
#import "../Sources/SSLocalData.h"
int main(int argc,const char *argv[]){@autoreleasepool{
    if(argc<2 || argc>3)return 2;NSArray *courses=argc==3 ? [NSPropertyListSerialization propertyListWithData:[NSData dataWithContentsOfFile:@(argv[2])] options:NSPropertyListImmutable format:NULL error:NULL] : SSReadPlist(@"courses.plist");NSMutableArray *documents=NSMutableArray.array;NSMutableDictionary *versions=NSMutableDictionary.dictionary,*cache=NSMutableDictionary.dictionary;SSGit *git=SSGit.new;git.recognitionSettings=@{@"mode":@"rules"};
    for(NSDictionary *course in courses){if([course[@"enabled"] isEqual:@NO] || ![course[@"path"] length])continue;NSError *error=nil;NSDictionary *scan=[git scanCourse:course cache:cache error:&error];if(!scan){fprintf(stderr,"Course read failed; no tasks or Git writes performed.\n");return 3;}for(NSDictionary *document in scan[@"documents"]) {NSMutableDictionary *copy=document.mutableCopy;NSMutableArray *refs=NSMutableArray.array;for(NSDictionary *candidate in scan[@"candidates"])if([candidate[@"path"] isEqual:document[@"path"]] && candidate[@"dateBasis"]){NSMutableDictionary *ref=[candidate[@"dateBasis"] mutableCopy];ref[@"line"]=candidate[@"line"];if([ref[@"date"] isKindOfClass:NSDate.class])ref[@"date"]=[NSISO8601DateFormatter.new stringFromDate:ref[@"date"]];[refs addObject:ref];}copy[@"references"]=refs;[documents addObject:copy];}versions[course[@"upstream"]]=scan[@"commit"];}
    NSString *folder=@(argv[1]);[NSFileManager.defaultManager createDirectoryAtPath:folder withIntermediateDirectories:YES attributes:@{NSFilePosixPermissions:@0700} error:NULL];
    NSData *data=[NSJSONSerialization dataWithJSONObject:documents options:NSJSONWritingPrettyPrinted error:NULL];if(![data writeToFile:[folder stringByAppendingPathComponent:@"documents.local.json"] options:NSDataWritingAtomic error:NULL])return 4;
    [[NSJSONSerialization dataWithJSONObject:versions options:NSJSONWritingPrettyPrinted error:NULL] writeToFile:[folder stringByAppendingPathComponent:@"versions.local.json"] options:NSDataWritingAtomic error:NULL];printf("Captured %lu teacher documents across %lu courses.\n",(unsigned long)documents.count,(unsigned long)versions.count);
}return 0;}
